# Production Configuration for Railway
spring:
  application:
    name: noteguard-backend

  # Database Configuration (Railway PostgreSQL)
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/noteguard}
    driver-class-name: org.postgresql.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Static Resources (serve React app)
  web:
    resources:
      static-locations: classpath:/static/,file:static/
  mvc:
    static-path-pattern: /**

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# JWT Configuration  
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Encryption Configuration
app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET:mySecretKey12345}

# Logging Configuration
logging:
  level:
    root: INFO
    com.noteguard.backend: INFO
