# Free MySQL Configuration (PlanetScale/FreeSQLDatabase)
spring:
  application:
    name: noteguard-backend

  # MySQL Configuration
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/noteguard}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Static Resources (serve React app)
  web:
    resources:
      static-locations: classpath:/static/,file:static/
  mvc:
    static-path-pattern: /**

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# JWT Configuration  
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Encryption Configuration
app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET:mySecretKey12345}

# Logging Configuration
logging:
  level:
    root: INFO
    com.noteguard.backend: INFO
