# Application Configuration
spring:
  application:
    name: noteguard-backend

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:noteguard}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # SQL Initialization
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Encryption Configuration
app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET:mySecretKey12345}

# Logging Configuration
logging:
  level:
    com.noteguard.backend: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
