# Production Configuration for Railway (PostgreSQL)
spring:
  application:
    name: noteguard-backend

  # PostgreSQL Database (FREE on Railway)
  datasource:
    url: ${DATABASE_URL} # Railway auto-provides this
    driver-class-name: org.postgresql.Driver
    # Railway provides the full URL with credentials, so we don't need separate username/password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # Same as your MySQL setup
    show-sql: true # Enable for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Static Resources (serve React app)
  web:
    resources:
      static-locations: classpath:/static/,file:static/
  mvc:
    static-path-pattern: /**

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# JWT Configuration (exactly same as before)
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Encryption Configuration (exactly same as before)
app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET:mySecretKey12345}

# Logging Configuration
logging:
  level:
    root: INFO
    com.noteguard.backend: INFO
